### PR TITLE
[DR-3031] Remove unused xlsx dependency

### PR DESCRIPTION
**Pull request by samanehsan**
https://broadworkbench.atlassian.net/browse/DR-3031

The `xlsx` library was added in one of the early Data Repo [commits](https://github.com/DataBiosphere/jade-data-repo-ui/commit/1fadea723327a1ad8fb24d069469d2f1dddd4fe5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) and is no longer used, so this PR removes the dependency. This resolves the dependabot alert: https://github.com/DataBiosphere/jade-data-repo-ui/security/dependabot/69

### CODE REVIEW

**Comment by nmalfroy** [comment]
I am kinda curious about the high line count.  I just ran an npm remove and had much fewer lines so i wonder what's going on

**Comment by samanehsan** [comment]
Hmm 🤔 I'll try this again as a sanity check!

**Comment by samanehsan** [comment]
I opened up a new branch and ran `npm uninstall xlsx` Is this consistent with what you saw @nmalfroy? https://github.com/DataBiosphere/jade-data-repo-ui/pull/1427/files 

It's still 34,000+ lines of changes 🤔

**Comment by samanehsan** [comment]
This is replaced by https://github.com/DataBiosphere/jade-data-repo-ui/pull/1427

**Pull request closed without merging**
