### PR TITLE
[DR-2735] Updated edit icons to have circle background

### PR DESCRIPTION
**Pull request by lu-c**
BEFORE
Screen Shot 2022-09-15 at 5 07 38 PM

AFTER
Screen Shot 2022-09-15 at 5 21 19 PM

### CODE REVIEW

**Review by otchet-broad — COMMENTED** [review]
I'm checking with UX to see if this is an acceptable implementation.  The ticket specifically says font-awesome pencil, but it occurs to me that the icon provided in [DR-2711](https://broadworkbench.atlassian.net/browse/DR-2711) looks more like font-awesome pen.  See: [pencil](https://fontawesome.com/icons/pencil?s=light&f=classic) and [pen](https://fontawesome.com/icons/pen?s=light&f=classic)

See clarification in the ticket.

**Comment by otchet-broad** [comment]
Looks like there's a license to use the Pro Icons.  See Lou's note in https://broadworkbench.atlassian.net/browse/DR-2735

**Review by otchet-broad — APPROVED** [review]
Nice work.

**Review by okotsopoulos — APPROVED** [review]
Thank you!

**Pull request merged**
