### PR TITLE
DC-819: Python script to populate small sample OMOP dataset

### PR DESCRIPTION
**Pull request by snf2ye**
https://broadworkbench.atlassian.net/browse/DC-819
______
Note: All data in the JSON files is synthetic OMOP data. 

Example: https://data.shelbee.bee.envs-terra.bio/datasets/0e743338-2663-4724-afae-b1953332b010
Ask me for access!

The populate_omop_data script can be used to generate JSON files with tabular OMOP data with a small test subset of OMOP data. It queries the BigQuery dataset and writes the results to json files to be used in the setup_ui_integration.py script.
**How does it work?**
(1) We start with the person table and pull a small subset of person ids
(2) Then we retrieve entries the occurrence tables (procedure_occurrence, condition_occurrence, drug_exposure) that map to the selected person ids, noting the referenced concept_ids in these entries
(3) We pull all the records from some of the reference tables (right now, just the domain table, but we could include others)
(4) We pull entries from the concept table that match referenced concept_ids from the occurrence tables
(5) We populate the concept_ancestor table with the ancestor_concept_id pulled from occurrence table's domain id and then the descendant_concept_id contains all the concepts form the concept table. This is the only table that we are fabricating.
(6) We write the results to json files
(7) We use the json files in the setup_ui_integration.py script to populate a test environment with the OMOP data

**How to use this script**
Note: this script overwrites the json files each time it is run
(1) Set the gcp_with_access variable to a google project that you have job big query access on
(2) Set the gcp_project and gcp_dataset variables to the project and dataset that you want to pull data from
(3) Set the person_limit variable to the number of person records you want to pull.  Note: Increasing this will very quickly increase the size of the tables, especially the concept table.

***BUT*, I hope that we don't regularly need to run this script. Instead, we'll just be able to use the setup_ui_integration script that will load the data pre-seeded in by the work in this PR.**

### CODE REVIEW

**Review by rjohanek — APPROVED** [review]
Thanks Shelby! I was able to run the populate_omop_data.py script to create the omop files locally and then I was able to create a dataset in my local TDR using the setup_ui_integration.py script!

**Comment by evansuslovich** [comment]
To run this script: DRAFT README 
```
python3 -m venv c:/path/to/myenv 
source c:/path/to/myenv/bin/activate
cd jade-data-repo-ui/tools/ui_integration
pip3 install -r requirements.txt
python3 setup_ui_integration.py
```

**Comment by snf2ye** [comment]
> To run this script: DRAFT README

@evansuslovich  Thanks for these instructions! I've added them to the readme.

**Review by evansuslovich — APPROVED** [review]
I've ran!

**Pull request merged**
