### PR TITLE
[DR-1826] Add region to snapshot table

### PR DESCRIPTION
**Pull request by samanehsan**
### Home tab:
Screen Shot 2021-05-24 at 12 32 19 PM

### Snapshots tab:
Screen Shot 2021-05-24 at 12 32 25 PM

### CODE REVIEW

**Review by tlangs — COMMENTED** [review]
Is there a reason `Datasets` has `Storage Regions`, but snapshots only has `Storage`?

**Comment by samanehsan** [comment]
@tlangs good point! Those should be consistent with each other so I'll change storage --> storage regions

**Review by tlangs — APPROVED** [review]

**Comment by samanehsan** [comment]
@tlangs I just fixed it!

**Review by nmalfroy — APPROVED** [review]
Same point as Trevyn.  Also, is there a ticket to link this to?

**Comment by samanehsan** [comment]
Yes! It's https://broadworkbench.atlassian.net/secure/RapidBoard.jspa?rapidView=44&projectKey=DR&modal=detail&selectedIssue=DR-1826

**Pull request merged**
