### PR TITLE
DR-2726 Updates AVN configuration from value in package.json

### PR DESCRIPTION
**Pull request by otchet-broad**

### CODE REVIEW

**Review by pshapiro4broad — COMMENTED** [review]
This looks fine (as far as I can tell) but I believe a JIRA ticket is required for all PRs in DSP repos that contain code deployed to production, even if what you're changing isn't code.

**Comment by otchet-broad** [comment]
Closing this request.  Will open a new PR with updates to the README when avn setup instructions are flushed out.

**Comment by nmalfroy** [comment]
FWIW @otchet-broad : I was able to get it to install correctly with your hint by doing:

1. `nvm install 10.0.0`
2. `rm -R ~/.avn` (to get rid of my existing install)
3. `nvm exec 10.0.0 npm install -g avn avn-nvm avn-n`
4. `nvm exec 10.0.0 avn setup`

We could update the README with that

**Comment by nmalfroy** [comment]
(and include your change from this PR)

**Review by nmalfroy — APPROVED** [review]
thanks for driving this!

**Review by okotsopoulos — APPROVED** [review]
Thanks for working on improving this set-up process!

**Pull request merged**
